### PR TITLE
Eslint issues fixed:

### PR DESCRIPTION
**Pull request by makhmudjon-inadullaev**
Eslint issues fixed for all bellow

- jsx-a11y/no-noninteractive-tabindex
- jsx-a11y/click-events-have-key-events
- jsx-a11y/no-static-element-interactions

## References

Issue: [#npm/datadog](https://app.datadoghq.com/dashboard/fq9-kaf-m3a?tpl_var_catalog_service=npm&from_ts=1677584886630&to_ts=1677588486630&live=true)

### CODE REVIEW

**Review by 20shivangi — COMMENTED** [review]
Change looks good to me. Can you please attach a video showing the page where these components are being used to show that it is working as expected ?

**Comment by makhmudjon-inadullaev** [comment]
<details>

<summary>Before changes</summary>

https://user-images.githubusercontent.com/91082111/222078535-b326f630-f615-4b7f-b6de-54a55fd4026e.mov

</details>

<details>

<summary>After changes</summary>

https://user-images.githubusercontent.com/91082111/222078628-8abb9754-5326-44d2-83fd-5ee69d56dc88.mov

</details>

cc: @20shivangi

**Comment by 20shivangi** [comment]
@makhmudjon-inadullaev why is there a difference in alignment of items in side window ?
Screenshot 2023-03-01 at 1 36 58 PM

**Review by 20shivangi — APPROVED** [review]
Perfect now 👏

**Review by Seryozha95 — APPROVED** [review]

**Pull request merged**
