### PR TITLE
Update downloading-and-installing-node-js-and-npm.mdx

### PR DESCRIPTION
**Pull request by AlexandraCruz**
Hi, there!
I was having an error where my Windows system wasn't recognizing the installed mvn-windows  throught  nvm --version command, even though my system variables seemed to be set up correctly. The error message mentioned something about nvm not being valid or recognized.

After searching online for solutions related to mvn-windows, system variables, and registry settings, I had a hunch that a simple restart might fix the problem. And it did!

I hope this tip saves someone else time in the future.  Cheers!

### CODE REVIEW

**Comment by kenshanta** [comment]
Hey @AlexandraCruz this is great. Did you pre-install nvm and _then_ execute _e.g_ the command `nvm --version` directly? (without any post-installation terminal/system reboot?)

**Comment by AlexandraCruz** [comment]
Hello. I preinstalled nvm.
Sheers!

**Comment by AlexandraCruz** [comment]
Sorry, I am lack of time to reproduce this issue.

**Comment by wraithgar** [comment]
I think in the absence of a reproducible use case here we should be hesitant to suggest rebooting your computer as part of the install process.

**Pull request closed without merging**
